### PR TITLE
Login Form

### PR DESCRIPTION
**Pull request by thatsddr**
### What's new:
- Login page with login and signup forms
- __tests__ folder organized in subfolders
- tests for login form, sign up form, and their helper functions
- updated header to show no nav links while on the login page
- added authentication context (but not really implemented yet)
- minor bugs fixed
- added tailwind package for forms styling

### How to test:

> requires node v. 14

- download the repository, 
-  navigate to the main folder;
- run ```npm i```;
- run ```npm run test```.

### CODE REVIEW

**Review by 5h3rr1ll — CHANGES_REQUESTED** [review]
When I run the test i saw this error. It's not too serious, but I thought I should mention it:

Screenshot 2021-03-18 at 20 58 50

Regarding the username restriction, I would really appreciate it if you @thatsddr & @Darjusch  could agree on something, what would accept my favorite username 😀

Screenshot 2021-03-18 at 20 59 00

Besides that, I would say: Good work!

**Comment by thatsddr** [comment]
Hey! 

Thanks for reviewing, I did not see this error when I ran the tests but I think I know where it comes from: I update the state in the helper functions and since the state update is asyncronous and jest unmounts the component immediately after the last test event fires, it throws that error.

To fix it we either rewrite the helper functions, their tests, and the sign up form logic or update the test to wait before unmounting the component.
But tbh since we have tests for the helper functions in another file that test doesn't make much sense.

Let me know what you think I should do, anyway I'll try to fix this either tomorrow afternoon or Saturday.

**Review by Darjusch — APPROVED** [review]

**Review by d-pettersson — APPROVED** [review]
Same note as  @5h3rr1ll - other than that, good work! Tests all passed

**Comment by thatsddr** [comment]
Fixed warning and updated password checking. Merging.

**Pull request merged**
